name: SFTP Deploy
  # You may pin to the exact commit or the version.
  # uses: wlixcc/SFTP-Deploy-Action@cf8d9e5b504ce4aab358e6231495c72a7dc18dcd
  uses: wlixcc/SFTP-Deploy-Action@1.1
  with:
    # username
    username: kimeljenek.hu
    # your sftp server
    server: 185.43.207.73
    # your sftp server port, default to 22
    port: 22
    # you can copy private_key from your *.pem file, keep format
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    # will put all file under this path
    local_path: ./site/* # default is ./*
    # files will copy to under remote_path
    remote_path: ./httpdocs # default is /
    # sftp args
    args: # optional
