# This is a basic workflow to help you get started with Actions

name: sftp 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      
      - name: create ssh folder
        run: mkdir -p /home/runner/.ssh/
       
      - name: create know hosts
        run: ssh-keyscan -H ${{secrets.FTP_SERVER}} > /home/runner/.ssh/known_hosts
       
      - name: create private key
        run: touch /home/runner/.ssh/private_key.pem
       
      - name: copy private key
        run: 'echo "${{secrets.FTP_SSH_PRIVATE_KEY}}" > /home/runner/.ssh/private_key.pem'
        #env:
        #  SSH_KEY: ${{secrets.FTP_SSH_PRIVATE_KEY}}

      - name: create sftp batch file
        run: touch /home/runner/sftp.batch

      - name: sftp batch file contents into env variable   
        run: 'echo "${{secrets.FTP_COMMANDS}}" > /home/runner/ftp.bat'
        #env:
        #  FTP_COMMANDS: ${{secrets.FTP_COMMANDS}}

      - name: change permission to private key
        run: chmod 400 /home/runner/.ssh/private_key.pem      

      - name: change permission to sftp batch file
        run: chmod 400 /home/runner/ftp.bat      

      # Runs a single command using the runners shell
      - name: sftp run
        run: sftp -r -i /home/runner/.ssh/private_key.pem -b /home/runner/ftp.bat ${{secrets.FTP_USERNAME}}@${{secrets.FTP_SERVER}}
        
